apiVersion: bifrost.peek8.io/v1alpha1
kind: LogSpace
metadata:
  labels:
    app.kubernetes.io/name: bifrost
    app.kubernetes.io/managed-by: kustomize
  name: logspace-sample
spec:
  targetNamespaces:
    - asgard
    - midgard
  pvc: 
    storageClass: "local-path"
  collector:
    storage: 
      size: "5Gi"
  loki:
    storage: 
      size: "5Gi"



