---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: logspaces.bifrost.peek8.io
spec:
  group: bifrost.peek8.io
  names:
    kind: LogSpace
    listKind: LogSpaceList
    plural: logspaces
    shortNames:
    - ls
    singular: logspace
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.state
      name: State
      type: string
    - jsonPath: .status.observedNamespaces
      name: Namespaces
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: LogSpace is the Schema for the logspaces API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: LogSpaceSpec defines the desired state of LogSpace.
            properties:
              collector:
                description: Collector controls how Grafana Alloy (or other collector)
                  is deployed.
                properties:
                  replicas:
                    description: Replicas for collector controller (if applicable).
                    format: int32
                    minimum: 1
                    type: integer
                  storage:
                    description: How much storage is needed for collector eg aloy
                      default is 5Gi
                    properties:
                      size:
                        description: Size of storage to be used in PVC Storage, eg
                          5Gi
                        type: string
                    type: object
                  type:
                    default: grafana-alloy
                    description: Type of collector. e.g. "grafana-alloy", "fluentbit",
                      "fluentd", Now only grafana-alloy is supported
                    enum:
                    - grafana-alloy
                    - fluentbit
                    - fluentd
                    type: string
                type: object
              grafana:
                description: Configuration for grafana
                properties:
                  storage:
                    description: Storage Configuration for loki
                    properties:
                      size:
                        description: Size of storage to be used in PVC Storage, eg
                          5Gi
                        type: string
                    type: object
                type: object
              loki:
                description: Configuration for Loki
                properties:
                  deploymentMode:
                    default: monolithic
                    enum:
                    - monolithic
                    - simpleScalable
                    - microservice
                    type: string
                  retentionPeriod:
                    default: 7d
                    description: Retention policy for logs, e.g. "7d", "30d"
                    type: string
                  schema:
                    description: Schema Configuration for loki
                    properties:
                      fromDate:
                        description: |-
                          Loki will use this storage schema for all logs from this date.
                          For example, if it is set to 2025-01-01, The schema will be used from 1st Jan, 2025
                          If not set, the current date will be used
                        type: string
                      objectStore:
                        default: filesystem
                        description: "The supported values are `filesystem, s3, gcs,
                          azure` where `filesystem`\tstore TSDB blocks locally on
                          disk\nand others store blocks in cloud object storage.\nFor
                          now only filesystem is supported"
                        enum:
                        - filesystem
                        - s3
                        - gcs
                        - azure
                        type: string
                    type: object
                  storage:
                    description: Storage Configuration for loki
                    properties:
                      size:
                        description: Size of storage to be used in PVC Storage, eg
                          5Gi
                        type: string
                    type: object
                type: object
              pvc:
                description: General PVC storage settings of the cluster
                properties:
                  storageClass:
                    description: |-
                      Storage Cluster of the cluster. if you are not sure the default storage class of the cluster,
                      you can get it by the command : $ kubectl get storageclass
                    type: string
                type: object
              targetNamespaces:
                description: Logs will be collected from the pods which are in these
                  Namespaces.
                items:
                  type: string
                type: array
            type: object
          status:
            description: LogSpaceStatus defines the observed state of LogSpace.
            properties:
              grafanaEndpoint:
                type: string
              lastError:
                description: LastError captures last reconciliation error (short message)
                type: string
              lastUpdated:
                description: LastUpdated timestamp for status
                format: date-time
                type: string
              lokiEndpoint:
                type: string
              observedNamespaces:
                description: ObservedNamespaces lists namespaces the operator selected/observed
                items:
                  type: string
                type: array
              phase:
                type: string
              state:
                description: State is a high-level state like "Ready", "Reconciling",
                  "Error"
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
